import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderPage from './components/partials/Header'
import FooterPage from './components/partials/Footer'
import Providers from './utils/provider/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Online Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`inter.className `}><Providers><HeaderPage />{children}<FooterPage /></Providers></body>
    </html>
  )
}
